### ISSUE TITLE
$scope.currentLanguage cannot be set in iPhone

### ISSUE THREAD

**Issue by bcgreiff** [jesusfreaks/fs-mobile#16]
During the angular-module definition of views the variable $scope.currentLanguage is set by
```javascript
$scope.currentLanguage = $translate.use().split('_')[0];
```
On iPhones this does not work and an error occures: 
`Error: undefined is not an object (evaluating '$translate.use().split')`

> __affected files:__
> states/event/event.js         line 18
> states/location/location.js  line 15

**Comment by dodophoenix** [comment]
Thx for investigation.
It is hopefully fixed.
Please try again.
Use settings to change language and after that open events screen.
If still not working 10 times click the language label to see debug info, and post the results
