### ISSUE TITLE
"reset content"-button causes empty "last update"-field

### ISSUE THREAD

**Issue by bcgreiff** [jesusfreaks/fs-mobile#20]
When the "reset content" button is clicked, the "last update" field is cleared and it stays empty until the next update is performed.

**Comment by bcgreiff** [comment]
Due to removed reset-button in current version this issue is deprecated

**Comment by dodophoenix** [comment]
Sounds like data json file is missing in the build...
Am 22.07.2015 16:54 schrieb "bcgreiff" <notifications@github.com>:
