### ISSUE TITLE
formatierbarer News Text

### ISSUE THREAD

**Issue by dodophoenix** [jesusfreaks/fs-mobile#31]
Der News-Text sollte formatierbar sein und neben Text auch weitere Elemente enthalten können. 
* Bilder 
* Links

WYSIWYG-Editor

**Comment by bcgreiff** [comment]
Vorschlag: Realisierung über Markdown

**Comment by dodophoenix** [comment]
+1 für Markdown

**Comment by nschwalbe** [comment]
Lieber kein Dummy Bild anzeigen, wenn es auch kein Bild gibt. Oder klar ersichtliche Platzhalter statt Bandbilder. (Betrifft auch Events)
